version: "3"

services:
      
  db:
    image: mysql:5.7.14
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=imasul_ecotech_db
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - default

networks:
  default:
    external:
      name: notebook
