version: "3"

services:
  db:
    build: .
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default

networks:
  default:
    external:
      name: notebook
