version: '3'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=1024M
      - UPLOAD_LIMIT=1024M
      - MAX_EXECUTION_TIME=0
      - UPLOAD_LIMI= 6096K
    networks:
      - default

networks:
  default:
    external:
      name: notebook