version: '3'

services:

  redis:
    image: redis
    container_name: redis-app
    # expose:
    #   - 6379
    ports:
      - 6379:6379
    networks:
      - default
    
networks:
  default:
    external:
      name: notebook
